### ISSUE TITLE
Typing of scope incorrect

### ISSUE THREAD

**Issue by jsjolen** [renarsvilnis/apple-sign-in-rest#3]
>  `scope?: "name" | "email"[];`

Is incorrect. You meant ` ("name" | "email")[]` but this is also not perfect :-).

Don't be clever, just unfold it:

`scope?: ["email","name"]|["name","email"]|["name"]|["email"]|[]`

**Comment by renarsvilnis** [comment]
Fixed. Thanks had missed it, unfolding might be the best solution, but a bit of an overkill, set it as `("name" | "email")[]`
