### ISSUE TITLE
Some minor typos in README.md

### ISSUE THREAD

**Issue by jsjolen** [renarsvilnis/apple-sign-in-rest#4]
In step 1.
>`privateKeyPath: '/Users/arnold/my-project/credentials/AuthKey.p8';`

Remove `;`.

In step 2.
>`const authorizationUrl = appleSignin.getAuthorizationUrl({`

The instance was declared as `appleSignIn` (note capital `I`).

>   `redirectUrl: "http://localhost:3000/auth/apple/callback",`

It's not `Url` it's `Uri`.

**Comment by renarsvilnis** [comment]
Typos fixed! Thanks for noticing!
